[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install && npm run build",
  "pip install flask numpy pillow scikit-learn joblib",
  "php artisan config:cache",
  "php artisan route:cache"
]

[phases.deploy]
cmds = ["php artisan migrate --force"]

[start]
cmd = "python3 ai_models/predict.py & php artisan serve --host=0.0.0.0 --port=$PORT"